
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Renari/pokecube-level-restriction/issues"
license="All rights reserved"

[[mods]]
    modId="pokecubelevelrestriction"
    version="${file.jarVersion}"
    displayName="Pokécube Level Restriction"
    authors="Arimil"
    description='''
    Makes it harder to catch Pokémob higher than your level.
    '''
    
[[dependencies.pokecubelevelrestriction]]
    modId="minecraft"
    mandatory=true
    versionRange="version_mc"
    ordering="NONE"
    side="BOTH"
[[dependencies.pokecubelevelrestriction]]
    modId="pokecube"
    mandatory=true
    versionRange="version_pokecube"
    ordering="NONE"
    side="BOTH"